volumes:
  cifs_mount:
    driver_opts:
      type: cifs
      o: "username=$PLEXSHARE_USERNAME,password=$PLEXSHARE_PASSWORD,vers=3.0"
      device: "$PLEX_STORAGE"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/dockerdata/sonarr/data:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PLEXSHARE_USERNAME=$PLEXSHARE_USERNAME
      - PLEXSHARE_PASSWORD=$PLEXSHARE_PASSWORD
      - $PLEX_STORAGE=$PLEX_STORAGE
    volumes:
      - /srv/dockerdata/radarr/data:/config
      - cifs_mount:/home/plexdata
    ports:
      - 7878:7878
    restart: unless-stopped