#volumes:
#  network_plex:
#    driver_opts:
#      type: cifs
#      o: "username=$PLEXSHARE_USERNAME,password=$PLEXSHARE_PASSWORD,vers=3.0"
#      device: "//$PLEX_STORAGE/D"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: /mnt/sonarr/config
        target: /config
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: /mnt/radarr/config
        target: /config
#      - network_plex:/home/plexdata
    ports:
      - 7878:7878
    restart: unless-stopped