services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/dockerdata/sonarr/data:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PLEXSHARE_USERNAME=$PLEXSHARE_USERNAME
      - PLEXSHARE_PASSWORD=$PLEXSHARE_PASSWORD
    volumes:
      - /srv/dockerdata/radarr/data:/config
      - cifs_mount:/home/data/
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  cifs_mount:
  driver: local
  driver_opts:
    type: cifs
    device: "//plexserver/d"
    o: "username=$PLEXSHARE_USERNAME,password=$PLEXSHARE_PASSWORD"