services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: /mnt/radarr/config
        target: /config
    ports:
      - 7878:7878
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]     
    restart: unless-stopped