services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - type: bind
        source: /mnt/sonarr/config
        target: /config
    ports:
      - 8989:8989
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]      
    restart: unless-stopped