version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - data:/srv/dockerdata/NGINXProxyManager/data
      - etc/letsencrypt:/srv/dockerdata/NGINXProxyManager/letsencrypt
    restart: unless-stopped