volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /srv/dockerdata/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
  prompve:
    image: prompve/prometheus-pve-exporter:latest
    container_name: prompve
    ports:
      - "9221:9221"
    volumes:
      - /srv/dockerdata/pve/pve.yml:/etc/prometheus/pve.yml
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    ports:
      - "8181:8181"
    volumes:
      - /srv/dockerdata/tautulli/config:/config
    environment:
      - PUID=<1000>
      - PGID=<1000>
      - TZ=<America/Toronto>