---
version: '3'

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/prometheus/data
      o: bind

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /mnt/prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - /mnt/grafana:/var/lib/grafanaa
    restart: unless-stopped
  prompve:
    container_name: prompve  
    image: prompve/prometheus-pve-exporter:latest
    ports:
      - "9221:9221"
    volumes:
      - /mnt/prompve/pve.yml:/etc/prometheus/pve.yml
    restart: unless-stopped
  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli:latest
    ports:
      - "8181:8181"
    volumes:
      - /mnt/tautulli/config:/config
    environment:
      - PUID=<1000>
      - PGID=<1000>
      - TZ=<America/Toronto>
    restart: unless-stopped