services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      #PUID: 1000
      #PGID: 1000
      - HOMEPAGE_VAR_PIHOLE_2_URL="{{HOMEPAGE_VAR_PIHOLE_2_URL}}"
      - HOMEPAGE_VAR_PIHOLE_1_API="{{HOMEPAGE_VAR_PIHOLE_1_API}}"
      - HOMEPAGE_VAR_PIHOLE_2_API="{{HOMEPAGE_VAR_PIHOLE_2_API}}"
      - HOMEPAGE_VAR_MYSPEED_URL="{{HOMEPAGE_VAR_MYSPEED_URL}}"
      - HOMEPAGE_VAR_MYSPEED_PASSWORD="{{HOMEPAGE_VAR_MYSPEED_PASSWORD}}"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: /mnt/homepage
        target: /app/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped