services:
  myspeed:
    image: docker.io/germannewsmaker/myspeed:latest
    container_name: myspeed
    ports:
    - 5216:5216
    restart: 
      unless-stopeed
    volumes:
      - /mnt/myspeed:/myspeed/data
