version: '3'

services:
  uptimekuma:
    image: elestio/uptime-kuma:latest
    container_name: uptimekuma
    ports:
      - 13001:3001
    volumes:
      - /mnt/uptime_kuma/data:/app/data
    restart: unless-stopped